import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Rahat",
      email: "rahat@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Admin",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456admin"),
      isAdmin: true,
    },
    {
      name: "abc",
      email: "abc@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "T Shirt",
      slug: "t-shirt",
      category: "Shirts",
      image: "/images/t_shart.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 12,
      description: "A popular shirt",
    },
    {
      name: "White T Shirt",
      slug: "white-t-shirt",
      category: "Shirts",
      image: "/images/t_shart.jpg",
      price: 99,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
      description: "A popular white shirt",
    },
    {
      name: "Black T Shirt ",
      slug: "black-t-shirt",
      category: "Shirts",
      image: "/images/t_shart_2.jpg",
      price: 39,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A Black T shirt",
    },
    {
      name: "Classic T Shirt",
      slug: "classic-t-shirt",
      category: "Shirts",
      image: "/images/t_shart_2.jpg",
      price: 69,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 50,
      description: "A Classic shirt",
    },
    {
      name: "Smart Watch",
      slug: "smart-watch",
      category: "watch",
      image: "/images/smart_watch.jpg",
      price: 70,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "A smart watch",
    },

    {
      name: "Gold Watch",
      slug: "gold-watch",
      category: "watch",
      image: "/images/watch_1.jpg",
      price: 90,
      brand: "Rolex",
      rating: 4.5,
      numReviews: 10,
      countInStock: 29,
      description: "Smart looking Watch",
    },
    {
      name: "Pure Perfume",
      slug: "pure-perfume",
      category: "perfume",
      image: "/images/perfume.jpg",
      price: 95,
      brand: "Calvin Klein",
      rating: 4.5,
      numReviews: 10,
      countInStock: 80,
      description: "A popular Perfume",
    },
    {
      name: "Red Rose",
      slug: "rose-perfume",
      category: "perfume",
      image: "/images/perfume_2.jpg",
      price: 75,
      brand: "Versace Eau",
      rating: 4.5,
      numReviews: 10,
      countInStock: 7,
      description: "A beautiful Versace Eau perfume",
    },
    {
      name: "Smart Watch v2",
      slug: "smart-watch-v2",
      category: "watch",
      image: "/images/smart_watch.jpg",
      price: 80,
      brand: "Patek Philippe",
      rating: 4.2,
      numReviews: 10,
      countInStock: 15,
      description: "A popular smart Watch v2",
    },
  ],
};
export default data;
